I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 34, in script call
    call poem
  File "game/script-poemgame.rpy", line 196, in script call
    python:
  File "renpy/common/00console.rpy", line 693, in script call
    python in _console:
  File "game/script.rpy", line 34, in script call
    call poem
  File "game/script-poemgame.rpy", line 196, in script call
    python:
  File "renpy/common/00console.rpy", line 693, in script call
    python in _console:
ScriptError: could not find label 'glitchpoem'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 34, in script call
    call poem
  File "game/script-poemgame.rpy", line 196, in script call
    python:
  File "renpy/common/00console.rpy", line 693, in script call
    python in _console:
  File "<string>", line 1, in script call
  File "/Users/ROSEW/Library/Application Support/Steam/steamapps/common/Doki Doki Literature Club/renpy/ast.py", line 1322, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 34, in script call
    call poem
  File "game/script-poemgame.rpy", line 196, in script call
    python:
  File "renpy/common/00console.rpy", line 693, in script call
    python in _console:
  File "<string>", line 1, in script call
  File "/Users/ROSEW/Library/Application Support/Steam/steamapps/common/Doki Doki Literature Club/renpy/script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'glitchpoem'.

Darwin-20.6.0-x86_64-i386-64bit
Ren'Py 6.99.12.4.2187
Doki Doki Sussy Club! 1.1.1
